# -*- coding: utf-8 -*-
"""LogicApp_Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YOSGcnJr0jsHbXCEjh0J96VfF7cK6uVW
"""

{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Send_Email_(V3)": {
                "inputs": {
                    "body": {
                        "Body": "<p class=\"editor-paragraph\">Hi,</p><p class=\"editor-paragraph\"></p><br><p class=\"editor-paragraph\">You have an alert:</p><p class=\"editor-paragraph\"><a class=\"editor-link\" href=\"https://\"><br></a></p>",
                        "From": "lindafangus@outlook.com",
                        "Subject": "ADF Pipeline Alert",
                        "To": "lindafangus@outlook.com"
                    },
                    "host": {
                        "connection": {
                            "name": "@parameters('$connections')['smtp']['connectionId']"
                        }
                    },
                    "method": "post",
                    "path": "/SendEmailV3"
                },
                "runAfter": {},
                "type": "ApiConnection"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "parameters": {
            "$connections": {
                "defaultValue": {},
                "type": "Object"
            }
        },
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "inputs": {
                    "schema": {
                        "properties": {
                            "body": {
                                "type": "string"
                            }
                        },
                        "type": "object"
                    }
                },
                "kind": "Http",
                "type": "Request"
            }
        }
    },
    "parameters": {
        "$connections": {
            "value": {
                "smtp": {
                    "connectionId": "/subscriptions/5ef66147-f269-44c5-bf57-142437268ec7/resourceGroups/lfapptest_group-8f62/providers/Microsoft.Web/connections/smtp",
                    "connectionName": "smtp",
                    "id": "/subscriptions/5ef66147-f269-44c5-bf57-142437268ec7/providers/Microsoft.Web/locations/eastus/managedApis/smtp"
                }
            }
        }
    }
}